name: .NET Core Deploy to App Engine

on:
  push:
    branches: master, Project-setup
    
jobs:
  build:
    name: Deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Google Cloud SDK
        uses: zxyle/publish-gae-action@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_SA_KEY }}
          gae_config_path: "./Backend/Nycflights-Backend/app.yaml"

      - name: Publish app to Google App Engine
        run: |
          gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud -q app deploy ./Backend/Nycflights-Backend/app.yaml --promote
  
